### ISSUE TITLE
Incorrect parsing of # sign

### ISSUE THREAD

**Issue by rzane** [theory/uri-db#7]
I posted in the sqitch-users group regarding an issue I was facing. I believe the behavior I was encountering was caused by a bug in uri-db.

Take this example script:
```perl
#!/usr/bin/perl
use URI::db;
my $uri = URI::db->new(shift);
my $format = "Host: %s\nDatabase: %s\nUser: %s\nPass: %s\n";
printf $format, $uri->host, $uri->dbname, $uri->user, $uri->password;
```

It works:

```
$ ./uri.pl db:firebird://sysdba:masterkey@myhost.com//path/to/db.fdb
Host: myhost.com
Database: C:/path/to/database.fdb
User: sysdba
Pass: masterkey
```

Now, say, for example, that my password includes a pound sign:

```
$ ./uri.pl db:firebird://sysdba:maste#rkey@myhost.com//path/to/db.fdb
Host: sysdba:maste
Database:
User:
Pass:
```

Unless there is a way to escape the pound sign, this seems to be unexpected behavior.

**Comment by theory** [comment]
It's a URI. You'll need to URI-escape it.

    > perl -MURI -E 'say URI->new(shift)->password' db:firebird://sysdba:mast%23key@myhost.com/c:\\path\\to\\database.fdb
    mast#key

**Comment by rzane** [comment]
Ahh! That makes complete sense. Thank you for all of your help.
