### ISSUE TITLE
Document mssql’s dbi_dsn(DRIVER) behavior.

### ISSUE THREAD

**Issue by drmuey** [theory/uri-db#9]
I created this issue for pull request #10 since I am unsure the proper place/way to do that for this project.

The behavior is:

`my $dsn = $u->dbi_dsn($driver);` set the driver and get DSN for $driver
`my $dns = $u->dbi_dsn;`  on subsequent calls: get DSN for $driver

`$driver` can be ODBC (default), ADO, or Sybase

**Comment by theory** [comment]
Done in 66bcb53f9b5563175d71985b63808fa28742e646 and f75f750033d7867ffdff2cb4894a1c5e9427d1d5. Thanks!
